// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: login.proto
#ifndef GRPC_login_2eproto__INCLUDED
#define GRPC_login_2eproto__INCLUDED

#include "login.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace login {

// RPC接口
class Login final {
 public:
  static constexpr char const* service_full_name() {
    return "login.Login";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status OnSignIn(::grpc::ClientContext* context, const ::login::SignInRequest& request, ::login::SignInResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::login::SignInResponse>> AsyncOnSignIn(::grpc::ClientContext* context, const ::login::SignInRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::login::SignInResponse>>(AsyncOnSignInRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::login::SignInResponse>> PrepareAsyncOnSignIn(::grpc::ClientContext* context, const ::login::SignInRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::login::SignInResponse>>(PrepareAsyncOnSignInRaw(context, request, cq));
    }
    virtual ::grpc::Status OnSignUp(::grpc::ClientContext* context, const ::login::SignUpRequest& request, ::login::SignUpResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::login::SignUpResponse>> AsyncOnSignUp(::grpc::ClientContext* context, const ::login::SignUpRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::login::SignUpResponse>>(AsyncOnSignUpRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::login::SignUpResponse>> PrepareAsyncOnSignUp(::grpc::ClientContext* context, const ::login::SignUpRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::login::SignUpResponse>>(PrepareAsyncOnSignUpRaw(context, request, cq));
    }
    virtual ::grpc::Status OnHeart(::grpc::ClientContext* context, const ::login::HeartRequest& request, ::login::HeartResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::login::HeartResponse>> AsyncOnHeart(::grpc::ClientContext* context, const ::login::HeartRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::login::HeartResponse>>(AsyncOnHeartRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::login::HeartResponse>> PrepareAsyncOnHeart(::grpc::ClientContext* context, const ::login::HeartRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::login::HeartResponse>>(PrepareAsyncOnHeartRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void OnSignIn(::grpc::ClientContext* context, const ::login::SignInRequest* request, ::login::SignInResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void OnSignIn(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::login::SignInResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void OnSignIn(::grpc::ClientContext* context, const ::login::SignInRequest* request, ::login::SignInResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void OnSignIn(::grpc::ClientContext* context, const ::login::SignInRequest* request, ::login::SignInResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void OnSignIn(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::login::SignInResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void OnSignIn(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::login::SignInResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void OnSignUp(::grpc::ClientContext* context, const ::login::SignUpRequest* request, ::login::SignUpResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void OnSignUp(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::login::SignUpResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void OnSignUp(::grpc::ClientContext* context, const ::login::SignUpRequest* request, ::login::SignUpResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void OnSignUp(::grpc::ClientContext* context, const ::login::SignUpRequest* request, ::login::SignUpResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void OnSignUp(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::login::SignUpResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void OnSignUp(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::login::SignUpResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void OnHeart(::grpc::ClientContext* context, const ::login::HeartRequest* request, ::login::HeartResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void OnHeart(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::login::HeartResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void OnHeart(::grpc::ClientContext* context, const ::login::HeartRequest* request, ::login::HeartResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void OnHeart(::grpc::ClientContext* context, const ::login::HeartRequest* request, ::login::HeartResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void OnHeart(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::login::HeartResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void OnHeart(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::login::HeartResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::login::SignInResponse>* AsyncOnSignInRaw(::grpc::ClientContext* context, const ::login::SignInRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::login::SignInResponse>* PrepareAsyncOnSignInRaw(::grpc::ClientContext* context, const ::login::SignInRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::login::SignUpResponse>* AsyncOnSignUpRaw(::grpc::ClientContext* context, const ::login::SignUpRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::login::SignUpResponse>* PrepareAsyncOnSignUpRaw(::grpc::ClientContext* context, const ::login::SignUpRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::login::HeartResponse>* AsyncOnHeartRaw(::grpc::ClientContext* context, const ::login::HeartRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::login::HeartResponse>* PrepareAsyncOnHeartRaw(::grpc::ClientContext* context, const ::login::HeartRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status OnSignIn(::grpc::ClientContext* context, const ::login::SignInRequest& request, ::login::SignInResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::login::SignInResponse>> AsyncOnSignIn(::grpc::ClientContext* context, const ::login::SignInRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::login::SignInResponse>>(AsyncOnSignInRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::login::SignInResponse>> PrepareAsyncOnSignIn(::grpc::ClientContext* context, const ::login::SignInRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::login::SignInResponse>>(PrepareAsyncOnSignInRaw(context, request, cq));
    }
    ::grpc::Status OnSignUp(::grpc::ClientContext* context, const ::login::SignUpRequest& request, ::login::SignUpResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::login::SignUpResponse>> AsyncOnSignUp(::grpc::ClientContext* context, const ::login::SignUpRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::login::SignUpResponse>>(AsyncOnSignUpRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::login::SignUpResponse>> PrepareAsyncOnSignUp(::grpc::ClientContext* context, const ::login::SignUpRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::login::SignUpResponse>>(PrepareAsyncOnSignUpRaw(context, request, cq));
    }
    ::grpc::Status OnHeart(::grpc::ClientContext* context, const ::login::HeartRequest& request, ::login::HeartResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::login::HeartResponse>> AsyncOnHeart(::grpc::ClientContext* context, const ::login::HeartRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::login::HeartResponse>>(AsyncOnHeartRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::login::HeartResponse>> PrepareAsyncOnHeart(::grpc::ClientContext* context, const ::login::HeartRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::login::HeartResponse>>(PrepareAsyncOnHeartRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void OnSignIn(::grpc::ClientContext* context, const ::login::SignInRequest* request, ::login::SignInResponse* response, std::function<void(::grpc::Status)>) override;
      void OnSignIn(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::login::SignInResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void OnSignIn(::grpc::ClientContext* context, const ::login::SignInRequest* request, ::login::SignInResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void OnSignIn(::grpc::ClientContext* context, const ::login::SignInRequest* request, ::login::SignInResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void OnSignIn(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::login::SignInResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void OnSignIn(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::login::SignInResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void OnSignUp(::grpc::ClientContext* context, const ::login::SignUpRequest* request, ::login::SignUpResponse* response, std::function<void(::grpc::Status)>) override;
      void OnSignUp(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::login::SignUpResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void OnSignUp(::grpc::ClientContext* context, const ::login::SignUpRequest* request, ::login::SignUpResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void OnSignUp(::grpc::ClientContext* context, const ::login::SignUpRequest* request, ::login::SignUpResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void OnSignUp(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::login::SignUpResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void OnSignUp(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::login::SignUpResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void OnHeart(::grpc::ClientContext* context, const ::login::HeartRequest* request, ::login::HeartResponse* response, std::function<void(::grpc::Status)>) override;
      void OnHeart(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::login::HeartResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void OnHeart(::grpc::ClientContext* context, const ::login::HeartRequest* request, ::login::HeartResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void OnHeart(::grpc::ClientContext* context, const ::login::HeartRequest* request, ::login::HeartResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void OnHeart(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::login::HeartResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void OnHeart(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::login::HeartResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::login::SignInResponse>* AsyncOnSignInRaw(::grpc::ClientContext* context, const ::login::SignInRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::login::SignInResponse>* PrepareAsyncOnSignInRaw(::grpc::ClientContext* context, const ::login::SignInRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::login::SignUpResponse>* AsyncOnSignUpRaw(::grpc::ClientContext* context, const ::login::SignUpRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::login::SignUpResponse>* PrepareAsyncOnSignUpRaw(::grpc::ClientContext* context, const ::login::SignUpRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::login::HeartResponse>* AsyncOnHeartRaw(::grpc::ClientContext* context, const ::login::HeartRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::login::HeartResponse>* PrepareAsyncOnHeartRaw(::grpc::ClientContext* context, const ::login::HeartRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_OnSignIn_;
    const ::grpc::internal::RpcMethod rpcmethod_OnSignUp_;
    const ::grpc::internal::RpcMethod rpcmethod_OnHeart_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status OnSignIn(::grpc::ServerContext* context, const ::login::SignInRequest* request, ::login::SignInResponse* response);
    virtual ::grpc::Status OnSignUp(::grpc::ServerContext* context, const ::login::SignUpRequest* request, ::login::SignUpResponse* response);
    virtual ::grpc::Status OnHeart(::grpc::ServerContext* context, const ::login::HeartRequest* request, ::login::HeartResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_OnSignIn : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_OnSignIn() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_OnSignIn() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnSignIn(::grpc::ServerContext* /*context*/, const ::login::SignInRequest* /*request*/, ::login::SignInResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOnSignIn(::grpc::ServerContext* context, ::login::SignInRequest* request, ::grpc::ServerAsyncResponseWriter< ::login::SignInResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_OnSignUp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_OnSignUp() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_OnSignUp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnSignUp(::grpc::ServerContext* /*context*/, const ::login::SignUpRequest* /*request*/, ::login::SignUpResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOnSignUp(::grpc::ServerContext* context, ::login::SignUpRequest* request, ::grpc::ServerAsyncResponseWriter< ::login::SignUpResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_OnHeart : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_OnHeart() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_OnHeart() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnHeart(::grpc::ServerContext* /*context*/, const ::login::HeartRequest* /*request*/, ::login::HeartResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOnHeart(::grpc::ServerContext* context, ::login::HeartRequest* request, ::grpc::ServerAsyncResponseWriter< ::login::HeartResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_OnSignIn<WithAsyncMethod_OnSignUp<WithAsyncMethod_OnHeart<Service > > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_OnSignIn : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_OnSignIn() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::login::SignInRequest, ::login::SignInResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::login::SignInRequest* request, ::login::SignInResponse* response) { return this->OnSignIn(context, request, response); }));}
    void SetMessageAllocatorFor_OnSignIn(
        ::grpc::experimental::MessageAllocator< ::login::SignInRequest, ::login::SignInResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::login::SignInRequest, ::login::SignInResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_OnSignIn() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnSignIn(::grpc::ServerContext* /*context*/, const ::login::SignInRequest* /*request*/, ::login::SignInResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* OnSignIn(
      ::grpc::CallbackServerContext* /*context*/, const ::login::SignInRequest* /*request*/, ::login::SignInResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* OnSignIn(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::login::SignInRequest* /*request*/, ::login::SignInResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_OnSignUp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_OnSignUp() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::login::SignUpRequest, ::login::SignUpResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::login::SignUpRequest* request, ::login::SignUpResponse* response) { return this->OnSignUp(context, request, response); }));}
    void SetMessageAllocatorFor_OnSignUp(
        ::grpc::experimental::MessageAllocator< ::login::SignUpRequest, ::login::SignUpResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::login::SignUpRequest, ::login::SignUpResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_OnSignUp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnSignUp(::grpc::ServerContext* /*context*/, const ::login::SignUpRequest* /*request*/, ::login::SignUpResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* OnSignUp(
      ::grpc::CallbackServerContext* /*context*/, const ::login::SignUpRequest* /*request*/, ::login::SignUpResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* OnSignUp(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::login::SignUpRequest* /*request*/, ::login::SignUpResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_OnHeart : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_OnHeart() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(2,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::login::HeartRequest, ::login::HeartResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::login::HeartRequest* request, ::login::HeartResponse* response) { return this->OnHeart(context, request, response); }));}
    void SetMessageAllocatorFor_OnHeart(
        ::grpc::experimental::MessageAllocator< ::login::HeartRequest, ::login::HeartResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(2);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::login::HeartRequest, ::login::HeartResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_OnHeart() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnHeart(::grpc::ServerContext* /*context*/, const ::login::HeartRequest* /*request*/, ::login::HeartResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* OnHeart(
      ::grpc::CallbackServerContext* /*context*/, const ::login::HeartRequest* /*request*/, ::login::HeartResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* OnHeart(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::login::HeartRequest* /*request*/, ::login::HeartResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_OnSignIn<ExperimentalWithCallbackMethod_OnSignUp<ExperimentalWithCallbackMethod_OnHeart<Service > > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_OnSignIn<ExperimentalWithCallbackMethod_OnSignUp<ExperimentalWithCallbackMethod_OnHeart<Service > > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_OnSignIn : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_OnSignIn() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_OnSignIn() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnSignIn(::grpc::ServerContext* /*context*/, const ::login::SignInRequest* /*request*/, ::login::SignInResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_OnSignUp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_OnSignUp() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_OnSignUp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnSignUp(::grpc::ServerContext* /*context*/, const ::login::SignUpRequest* /*request*/, ::login::SignUpResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_OnHeart : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_OnHeart() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_OnHeart() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnHeart(::grpc::ServerContext* /*context*/, const ::login::HeartRequest* /*request*/, ::login::HeartResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_OnSignIn : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_OnSignIn() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_OnSignIn() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnSignIn(::grpc::ServerContext* /*context*/, const ::login::SignInRequest* /*request*/, ::login::SignInResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOnSignIn(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_OnSignUp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_OnSignUp() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_OnSignUp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnSignUp(::grpc::ServerContext* /*context*/, const ::login::SignUpRequest* /*request*/, ::login::SignUpResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOnSignUp(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_OnHeart : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_OnHeart() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_OnHeart() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnHeart(::grpc::ServerContext* /*context*/, const ::login::HeartRequest* /*request*/, ::login::HeartResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOnHeart(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_OnSignIn : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_OnSignIn() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->OnSignIn(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_OnSignIn() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnSignIn(::grpc::ServerContext* /*context*/, const ::login::SignInRequest* /*request*/, ::login::SignInResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* OnSignIn(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* OnSignIn(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_OnSignUp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_OnSignUp() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->OnSignUp(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_OnSignUp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnSignUp(::grpc::ServerContext* /*context*/, const ::login::SignUpRequest* /*request*/, ::login::SignUpResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* OnSignUp(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* OnSignUp(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_OnHeart : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_OnHeart() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(2,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->OnHeart(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_OnHeart() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnHeart(::grpc::ServerContext* /*context*/, const ::login::HeartRequest* /*request*/, ::login::HeartResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* OnHeart(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* OnHeart(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_OnSignIn : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_OnSignIn() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::login::SignInRequest, ::login::SignInResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::login::SignInRequest, ::login::SignInResponse>* streamer) {
                       return this->StreamedOnSignIn(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_OnSignIn() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status OnSignIn(::grpc::ServerContext* /*context*/, const ::login::SignInRequest* /*request*/, ::login::SignInResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedOnSignIn(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::login::SignInRequest,::login::SignInResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_OnSignUp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_OnSignUp() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::login::SignUpRequest, ::login::SignUpResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::login::SignUpRequest, ::login::SignUpResponse>* streamer) {
                       return this->StreamedOnSignUp(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_OnSignUp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status OnSignUp(::grpc::ServerContext* /*context*/, const ::login::SignUpRequest* /*request*/, ::login::SignUpResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedOnSignUp(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::login::SignUpRequest,::login::SignUpResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_OnHeart : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_OnHeart() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::login::HeartRequest, ::login::HeartResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::login::HeartRequest, ::login::HeartResponse>* streamer) {
                       return this->StreamedOnHeart(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_OnHeart() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status OnHeart(::grpc::ServerContext* /*context*/, const ::login::HeartRequest* /*request*/, ::login::HeartResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedOnHeart(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::login::HeartRequest,::login::HeartResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_OnSignIn<WithStreamedUnaryMethod_OnSignUp<WithStreamedUnaryMethod_OnHeart<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_OnSignIn<WithStreamedUnaryMethod_OnSignUp<WithStreamedUnaryMethod_OnHeart<Service > > > StreamedService;
};

}  // namespace login


#endif  // GRPC_login_2eproto__INCLUDED
