# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
cc_library(
    name = "cache",
    srcs = ["cache.cc"],
    hdrs = ["cache.h"],
    deps = ["//util:util"],
    visibility = ["//visibility:public"],
)